### ISSUE TITLE
ESP8266 - Cannot connect to Blynk cloud.. (Disconnected)

### ISSUE THREAD

**Issue by gojigeje** [vshymanskyy/blynk-library-lua#1]
Hi, thanks for the library
I tried this on my two ESP modules, but none oh them seems to be working.
It only displays `Connecting` and then `Disconnected`.

Board used:
1. ESP8266-01 Module
2. NodeMCU Devboard, Lolin V3

Firmware Info:
```
NodeMCU custom build by frightanic.com
	branch: master
	commit: c708828bbe853764b9de58fb8113a70f5a24002d
	SSL: false
	modules: cron,crypto,encoder,file,gpio,mqtt,net,node,rtctime,sntp,tmr,uart,wifi
 build created on 2018-11-07 05:01
 powered by Lua 5.1.4 on SDK 2.2.1(6ab97e9)
```

Output Log:
```
> dofile("run.lua")
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ for Lua v0.1.3

Connecting WiFi...
> Connecting Blynk...
Disconnected.
Connecting Blynk...
Disconnected.
Connecting Blynk...
Disconnected.
Connecting Blynk...
Disconnected.
Connecting Blynk...
...
...
(repeats..)
```
Could you look into this?

**Comment by vshymanskyy** [comment]
Can not reproduce. Works as expected when following the provided instructions.
Please try general connection troubleshooting, as per Blynk docs:
> Try running command `telnet blynk-cloud.com` 80 from your PC, connected to the same network as your hardware. You should see something like: `Connected to blynk-cloud.com`
